title: guelfoweb
description: "Random notes"
author: guelfoweb
url: "https://guelfoweb.github.io"

# Tema di default
theme: minima

# Impostazioni di build
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
