title: guelfoweb
description: "random notes"
author: guelfoweb
url: ""
baseurl: ""
theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: feed.xml     # nome file (default: feed.xml)
  title: "guelfoweb"
  description: "random notes"
